export const ISA_FUND_TYPES = [
   'UK Equity Fund',
   'Global Equity Fund',
   'US Equity Growth Fund',
   'European Equity Fund',
   'Emerging Markets Equity Fund',
   'Sustainable ESG Equity Fund',
   'Small Cap Equity Fund',
   'UK Government Bond Fund',
   'Corporate Bond Fund',
   'Global Aggregate Bond Fund',
   'Inflation-Linked Bond Fund',
   'High Yield Bond Fund',
   'Cautious Balanced Fund',
   'Moderate Balanced Fund',
   'Adventurous Balanced Fund',
   'Growth & Income Fund',
   'Sustainable Growth Fund',
   'Climate Impact Fund',
   'Ethical Opportunities Fund',
   'Technology & Innovation Fund',
   'Healthcare Fund',
   'Property & Infrastructure Fund',
   'Commodities Fund',
   'Clean Energy Fund'
]
